### ISSUE TITLE
Switch reference to oidc-client-js to oidc-client-ts

### ISSUE THREAD

**Issue by danroth27** [DuendeSoftware/docs.duendesoftware.com#235]
In the section on setting up auth for a frontend JS app that has no backend it suggests to use oidc-client.js: https://docs.duendesoftware.com/identityserver/v6/quickstarts/js_clients/js_without_backend/#reference-oidc-client. Should this be pointing folks to oidc-client-ts instead? The oidc-client-js repo readme says the library is no longer maintained and seems to indicate oidc-client-ts is the replacement.

**Comment by brockallen** [comment]
Hi Dan. 

> Should this be pointing folks to oidc-client-ts instead

That's a good question. oidc-client-ts is a fork of oidc-client-js, but I do not see it [OIDC certified](https://openid.net/certification/#RPs). I've not been using it or following the repo recently, and so I can't speak to the quality level.

oidc-client-js works and as of this post we've not received any reports or notifications of any problems with it (security or otherwise).

So unfortunately I don't have a good answer for you.

Regardless, the approach of doing OAuth/OIDC in the browser is not what we'd recommend anymore. Rather, using a BFF approach is much more secure: https://blog.duendesoftware.com/posts/20210326_bff/

**Comment by brockallen** [comment]
Anything else to follow up on here @danroth27?

**Comment by danroth27** [comment]
Nope, it sounds like you're saying the link to oidc-client-js in the Duende docs is intentional, so I think this issue can just be closed.
